#!/usr/bin/env bash
#
# Regenerate every services/Tims.Platform/db/flip-ddl/*.sql from the committed production baseline (#328).
#
# Each flip-ddl file is generated by scripts/db/extract-table-ddl.mjs and records how on its line 2:
#   -- Regenerate: node scripts/db/extract-table-ddl.mjs <table> [<table>...]
# Re-capturing the baseline (scripts/db/schema-baseline.sh capture) changes their source, so they must be
# regenerated in the same change — tests/db/extract-table-ddl.test.ts fails otherwise.
#
# The line is PARSED, never executed: it must match the exact shape above with plain lower-case SQL
# identifiers, or this script refuses. A file without a valid line is an error, not a skip.
#
# EXIT  0 = every file regenerated · 2 = could not run (bad/missing header, generator failure)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIR="$REPO_ROOT/services/Tims.Platform/db/flip-ddl"
PREFIX='-- Regenerate: node scripts/db/extract-table-ddl.mjs '

shopt -s nullglob
files=("$DIR"/*.sql)
if [ "${#files[@]}" -eq 0 ]; then
  echo "✖ COULD NOT RUN — no flip-ddl files under ${DIR#"$REPO_ROOT"/}" >&2
  exit 2
fi

for f in "${files[@]}"; do
  rel="${f#"$REPO_ROOT"/}"
  line="$(sed -n 2p "$f")"
  if [[ "$line" != "$PREFIX"* ]]; then
    echo "✖ COULD NOT RUN — $rel line 2 is not a '-- Regenerate:' line" >&2
    exit 2
  fi
  tables="${line#"$PREFIX"}"
  if ! [[ "$tables" =~ ^[a-z_][a-z0-9_]*( [a-z_][a-z0-9_]*)*$ ]]; then
    echo "✖ COULD NOT RUN — $rel has an unexpected table list on its Regenerate line" >&2
    exit 2
  fi
  # shellcheck disable=SC2086 # word-splitting the validated identifier list is the point
  # --out is resolved against the repo root by the generator, so it takes the repo-relative path.
  if ! node "$REPO_ROOT/scripts/db/extract-table-ddl.mjs" --out "$rel" $tables >/dev/null; then
    echo "✖ COULD NOT RUN — extract-table-ddl.mjs failed for $rel" >&2
    exit 2
  fi
  echo "✓ regenerated $rel ($tables)"
done
