import { defineConfig, devices } from '@playwright/test';
import { readStack } from './lib/stack';

// The stack comes from scripts/e2e/up.sh, which writes e2e/.state/stack.json. readStack() refuses
// any non-local URL, so a mis-set environment can never point the suite at production.
const stack = readStack();
const isCI = !!process.env.CI;

export default defineConfig({
  testDir: './specs',
  globalSetup: './global-setup.ts',
  // The journeys are ordered, stateful stories (a company is created, then staffed, then hires).
  // Each project runs its files serially; parallelism would only race the shared tenant.
  fullyParallel: false,
  workers: 1,
  forbidOnly: isCI,
  // One retry in CI absorbs a genuinely flaky navigation without hiding a real failure: a retried
  // pass is reported as "flaky" in the HTML report, never silently as green.
  retries: isCI ? 1 : 0,
  timeout: 120_000,
  expect: { timeout: 20_000 },
  reporter: isCI
    ? [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }], ['github']]
    : [['list'], ['html', { open: 'never', outputFolder: 'playwright-report' }]],
  outputDir: 'test-results',
  use: {
    baseURL: stack.baseURL,
    // The stack serves TLS with a throwaway CA generated by up.sh.
    ignoreHTTPSErrors: true,
    locale: 'es-CO',
    timezoneId: 'America/Bogota',
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    actionTimeout: 20_000,
    navigationTimeout: 45_000,
  },
  projects: [
    {
      name: 'company',
      testMatch: /company\/.*\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } },
    },
    {
      // The candidate journey applies to the vacancy the company journey published, so it only
      // runs once that journey has run (it is skipped, not failed, if the company journey fails).
      name: 'candidate',
      testMatch: /candidate\/.*\.spec\.ts/,
      dependencies: ['company'],
      use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } },
    },
  ],
});
