-- Tenant isolation via Postgres RLS. See docs/security/RLS-MIGRATION-PLAN.md.
-- VERIFIED empirically on the live Supabase instance (cross-org read blocked, WITH CHECK
-- blocks cross-org write, unset GUC fails closed with no error).
--
-- ENFORCEMENT MODEL: the app connects as the privileged `postgres` role (the role the
-- Supabase Supavisor pooler authenticates). Tenant queries run `SET LOCAL ROLE app_tenant`
-- per transaction (see packages/db/src/tenant-client.ts) so they execute as the NON-bypass
-- role and RLS applies. This needs no custom-role login (Supavisor rejects those) and no
-- second connection pool. `postgres` keeps BYPASSRLS for context-builder / platform /
-- worker queries, so enabling RLS is a NO-OP for them.
--
-- The policy uses NULLIF(current_setting(...), '')::uuid: an unset/empty GUC becomes NULL so
-- every row is hidden (fail closed) instead of raising a uuid cast error.

-- 1) Non-login privilege role used only as the SET LOCAL ROLE target for RLS. No password /
--    no login (it never authenticates directly). GRANT it to postgres so postgres can SET ROLE.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='app_tenant') THEN
    CREATE ROLE app_tenant NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  END IF;
END $$;
GRANT app_tenant TO postgres;

GRANT USAGE ON SCHEMA public TO app_tenant;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_tenant;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_tenant;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_tenant;

-- 2) Tenant tables scoped directly by organization_id (71 tables)
ALTER TABLE "action_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "action_plans" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "action_plans";
CREATE POLICY tenant_isolation ON "action_plans" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "ai_agent_org_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_agent_org_configs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ai_agent_org_configs";
CREATE POLICY tenant_isolation ON "ai_agent_org_configs" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "ai_agent_usage_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_agent_usage_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "ai_agent_usage_logs";
CREATE POLICY tenant_isolation ON "ai_agent_usage_logs" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "alert_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "alert_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "alert_rules";
CREATE POLICY tenant_isolation ON "alert_rules" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "alerts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "alerts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "alerts";
CREATE POLICY tenant_isolation ON "alerts" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_keys" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "api_keys";
CREATE POLICY tenant_isolation ON "api_keys" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "applications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "applications";
CREATE POLICY tenant_isolation ON "applications" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "assessment_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessment_assignments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "assessment_assignments";
CREATE POLICY tenant_isolation ON "assessment_assignments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "assessment_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessment_results" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "assessment_results";
CREATE POLICY tenant_isolation ON "assessment_results" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "assessment_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "assessment_types" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "assessment_types";
CREATE POLICY tenant_isolation ON "assessment_types" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "audit_logs";
CREATE POLICY tenant_isolation ON "audit_logs" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "benefit_enrollments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "benefit_enrollments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "benefit_enrollments";
CREATE POLICY tenant_isolation ON "benefit_enrollments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "benefit_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "benefit_plans" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "benefit_plans";
CREATE POLICY tenant_isolation ON "benefit_plans" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "billing_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_profiles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "billing_profiles";
CREATE POLICY tenant_isolation ON "billing_profiles" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "business_units" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_units" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "business_units";
CREATE POLICY tenant_isolation ON "business_units" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "calibration_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calibration_sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "calibration_sessions";
CREATE POLICY tenant_isolation ON "calibration_sessions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "candidate_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_documents" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_documents";
CREATE POLICY tenant_isolation ON "candidate_documents" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "candidate_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidate_tags" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidate_tags";
CREATE POLICY tenant_isolation ON "candidate_tags" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "candidates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "candidates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "candidates";
CREATE POLICY tenant_isolation ON "candidates" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "certificates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "certificates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "certificates";
CREATE POLICY tenant_isolation ON "certificates" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "coaching_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "coaching_sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "coaching_sessions";
CREATE POLICY tenant_isolation ON "coaching_sessions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "commitments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "commitments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "commitments";
CREATE POLICY tenant_isolation ON "commitments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "companies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "companies";
CREATE POLICY tenant_isolation ON "companies" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "connector_syncs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "connector_syncs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "connector_syncs";
CREATE POLICY tenant_isolation ON "connector_syncs" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "connectors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "connectors" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "connectors";
CREATE POLICY tenant_isolation ON "connectors" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "courses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "courses";
CREATE POLICY tenant_isolation ON "courses" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "critical_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "critical_roles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "critical_roles";
CREATE POLICY tenant_isolation ON "critical_roles" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "employee_compensations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "employee_compensations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "employee_compensations";
CREATE POLICY tenant_isolation ON "employee_compensations" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "enrollments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "enrollments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "enrollments";
CREATE POLICY tenant_isolation ON "enrollments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "feature_flags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feature_flags" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "feature_flags";
CREATE POLICY tenant_isolation ON "feature_flags" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "feedbacks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "feedbacks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "feedbacks";
CREATE POLICY tenant_isolation ON "feedbacks" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "fit_scores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fit_scores" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "fit_scores";
CREATE POLICY tenant_isolation ON "fit_scores" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "interview_scorecards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_scorecards" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interview_scorecards";
CREATE POLICY tenant_isolation ON "interview_scorecards" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "interview_summaries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_summaries" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interview_summaries";
CREATE POLICY tenant_isolation ON "interview_summaries" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "interviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interviews" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interviews";
CREATE POLICY tenant_isolation ON "interviews" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoices" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoices";
CREATE POLICY tenant_isolation ON "invoices" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "job_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_profiles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "job_profiles";
CREATE POLICY tenant_isolation ON "job_profiles" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "key_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "key_results" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "key_results";
CREATE POLICY tenant_isolation ON "key_results" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "leader_commitments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "leader_commitments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "leader_commitments";
CREATE POLICY tenant_isolation ON "leader_commitments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "learning_paths" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "learning_paths" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "learning_paths";
CREATE POLICY tenant_isolation ON "learning_paths" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "legal_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "legal_checks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "legal_checks";
CREATE POLICY tenant_isolation ON "legal_checks" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "nine_box_evaluations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "nine_box_evaluations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "nine_box_evaluations";
CREATE POLICY tenant_isolation ON "nine_box_evaluations" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "notifications";
CREATE POLICY tenant_isolation ON "notifications" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "offer_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "offer_approvals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "offer_approvals";
CREATE POLICY tenant_isolation ON "offer_approvals" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "offers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "offers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "offers";
CREATE POLICY tenant_isolation ON "offers" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "okrs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "okrs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "okrs";
CREATE POLICY tenant_isolation ON "okrs" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "onboarding_check_ins" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "onboarding_check_ins" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "onboarding_check_ins";
CREATE POLICY tenant_isolation ON "onboarding_check_ins" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "onboarding_plans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "onboarding_plans" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "onboarding_plans";
CREATE POLICY tenant_isolation ON "onboarding_plans" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "onboarding_tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "onboarding_tasks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "onboarding_tasks";
CREATE POLICY tenant_isolation ON "onboarding_tasks" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "pipeline_stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pipeline_stages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "pipeline_stages";
CREATE POLICY tenant_isolation ON "pipeline_stages" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "platform_invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "platform_invitations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "platform_invitations";
CREATE POLICY tenant_isolation ON "platform_invitations" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "preemployment_validations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "preemployment_validations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "preemployment_validations";
CREATE POLICY tenant_isolation ON "preemployment_validations" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "proctoring_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "proctoring_sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "proctoring_sessions";
CREATE POLICY tenant_isolation ON "proctoring_sessions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "publication_channels" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "publication_channels" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "publication_channels";
CREATE POLICY tenant_isolation ON "publication_channels" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "recognitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "recognitions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "recognitions";
CREATE POLICY tenant_isolation ON "recognitions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "referrals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "referrals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "referrals";
CREATE POLICY tenant_isolation ON "referrals" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "roles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "roles";
CREATE POLICY tenant_isolation ON "roles" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "salary_adjustments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "salary_adjustments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "salary_adjustments";
CREATE POLICY tenant_isolation ON "salary_adjustments" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "salary_bands" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "salary_bands" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "salary_bands";
CREATE POLICY tenant_isolation ON "salary_bands" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "sessions";
CREATE POLICY tenant_isolation ON "sessions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "stage_movements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stage_movements" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "stage_movements";
CREATE POLICY tenant_isolation ON "stage_movements" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "subscriptions";
CREATE POLICY tenant_isolation ON "subscriptions" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "successors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "successors" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "successors";
CREATE POLICY tenant_isolation ON "successors" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "survey_responses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "survey_responses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "survey_responses";
CREATE POLICY tenant_isolation ON "survey_responses" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "surveys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "surveys" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "surveys";
CREATE POLICY tenant_isolation ON "surveys" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "sync_errors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sync_errors" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "sync_errors";
CREATE POLICY tenant_isolation ON "sync_errors" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teams" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "teams";
CREATE POLICY tenant_isolation ON "teams" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "users";
CREATE POLICY tenant_isolation ON "users" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "vacancies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vacancies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "vacancies";
CREATE POLICY tenant_isolation ON "vacancies" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "vacancy_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vacancy_approvals" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "vacancy_approvals";
CREATE POLICY tenant_isolation ON "vacancy_approvals" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);
ALTER TABLE "webhooks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhooks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "webhooks";
CREATE POLICY tenant_isolation ON "webhooks" USING (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

-- 3) organizations: scope by its own id
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "organizations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "organizations";
CREATE POLICY tenant_isolation ON "organizations" USING (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid) WITH CHECK (id = NULLIF(current_setting('app.current_org_id', true), '')::uuid);

-- 4) Child/join tables: scope via parent organization_id
ALTER TABLE "calibration_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calibration_members" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "calibration_members";
CREATE POLICY tenant_isolation ON "calibration_members" USING (EXISTS (SELECT 1 FROM "calibration_sessions" par WHERE par.id = "calibration_members"."session_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "calibration_sessions" par WHERE par.id = "calibration_members"."session_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "calibration_votes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calibration_votes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "calibration_votes";
CREATE POLICY tenant_isolation ON "calibration_votes" USING (EXISTS (SELECT 1 FROM "calibration_sessions" par WHERE par.id = "calibration_votes"."session_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "calibration_sessions" par WHERE par.id = "calibration_votes"."session_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "interview_evaluators" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "interview_evaluators" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "interview_evaluators";
CREATE POLICY tenant_isolation ON "interview_evaluators" USING (EXISTS (SELECT 1 FROM "interviews" par WHERE par.id = "interview_evaluators"."interview_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "interviews" par WHERE par.id = "interview_evaluators"."interview_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "invoice_line_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_line_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "invoice_line_items";
CREATE POLICY tenant_isolation ON "invoice_line_items" USING (EXISTS (SELECT 1 FROM "invoices" par WHERE par.id = "invoice_line_items"."invoice_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "invoices" par WHERE par.id = "invoice_line_items"."invoice_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "learning_path_courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "learning_path_courses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "learning_path_courses";
CREATE POLICY tenant_isolation ON "learning_path_courses" USING (EXISTS (SELECT 1 FROM "learning_paths" par WHERE par.id = "learning_path_courses"."path_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "learning_paths" par WHERE par.id = "learning_path_courses"."path_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "role_permissions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "role_permissions";
CREATE POLICY tenant_isolation ON "role_permissions" USING (EXISTS (SELECT 1 FROM "roles" par WHERE par.id = "role_permissions"."role_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "roles" par WHERE par.id = "role_permissions"."role_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "user_roles";
CREATE POLICY tenant_isolation ON "user_roles" USING (EXISTS (SELECT 1 FROM "roles" par WHERE par.id = "user_roles"."role_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "roles" par WHERE par.id = "user_roles"."role_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "user_teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_teams" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "user_teams";
CREATE POLICY tenant_isolation ON "user_teams" USING (EXISTS (SELECT 1 FROM "teams" par WHERE par.id = "user_teams"."team_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "teams" par WHERE par.id = "user_teams"."team_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));
ALTER TABLE "notification_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_preferences" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON "notification_preferences";
CREATE POLICY tenant_isolation ON "notification_preferences" USING (EXISTS (SELECT 1 FROM "users" par WHERE par.id = "notification_preferences"."user_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid)) WITH CHECK (EXISTS (SELECT 1 FROM "users" par WHERE par.id = "notification_preferences"."user_id" AND par.organization_id = NULLIF(current_setting('app.current_org_id', true), '')::uuid));

-- 5) Global system catalogs — intentionally NO RLS (read-only reference / platform):
--    ai_agents, permissions, platform_owner_emails
