// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tims.Infrastructure.Hris;

#nullable disable

namespace Tims.Infrastructure.Migrations
{
    [DbContext(typeof(HrisDbContext))]
    [Migration("20260716000000_hris_domain")]
    partial class hris_domain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tims.Infrastructure.Hris.HrisConnectorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FieldMap")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_map")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("LastSyncRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_sync_run_id");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SecretRef")
                        .HasColumnType("text")
                        .HasColumnName("secret_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Subdomain")
                        .HasColumnType("text")
                        .HasColumnName("subdomain");

                    b.Property<string>("SyncCadence")
                        .HasColumnType("text")
                        .HasColumnName("sync_cadence");

                    b.Property<string>("SyncCursor")
                        .HasColumnType("text")
                        .HasColumnName("sync_cursor");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_hris_connectors_org_provider");

                    b.ToTable("hris_connectors", (string)null);
                });

            modelBuilder.Entity("Tims.Infrastructure.Hris.HrisExternalEmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasColumnName("division");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("text")
                        .HasColumnName("employment_status");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hire_date");

                    b.Property<bool>("IsDeletedInSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted_in_source");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LastSyncRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_sync_run_id");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_hash");

                    b.Property<string>("SupervisorExternalId")
                        .HasColumnType("text")
                        .HasColumnName("supervisor_external_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkEmail")
                        .HasColumnType("text")
                        .HasColumnName("work_email");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId")
                        .HasDatabaseName("ix_hris_external_employees_connector");

                    b.HasIndex("OrganizationId", "ConnectorId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_hris_external_employees_org_connector_external");

                    b.ToTable("hris_external_employees", (string)null);
                });

            modelBuilder.Entity("Tims.Infrastructure.Hris.HrisSyncRecordErrorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_type");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("sync_run_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId")
                        .HasDatabaseName("ix_hris_sync_record_errors_connector");

                    b.HasIndex("SyncRunId")
                        .HasDatabaseName("ix_hris_sync_record_errors_sync_run");

                    b.ToTable("hris_sync_record_errors", (string)null);
                });

            modelBuilder.Entity("Tims.Infrastructure.Hris.HrisSyncRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CursorAfter")
                        .HasColumnType("text")
                        .HasColumnName("cursor_after");

                    b.Property<string>("CursorBefore")
                        .HasColumnType("text")
                        .HasColumnName("cursor_before");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RecordsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_failed");

                    b.Property<int>("RecordsSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_seen");

                    b.Property<int>("RecordsUpserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("records_upserted");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId")
                        .HasDatabaseName("ix_hris_sync_runs_connector");

                    b.HasIndex("OrganizationId", "ConnectorId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_hris_sync_runs_org_connector_idempotency");

                    b.ToTable("hris_sync_runs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
