/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WhoAmI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExternalWhoAmI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/assessment-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExternalGetAssessmentResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/assessment-results/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ExternalGetAssessmentResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/validations/{validationId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExternalSubmitValidationResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingListInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingGetInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingGetUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingGetCurrentPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BillingGetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StripeBillingWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingCreateCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingCreatePortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/cancel-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BillingCancelSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetFunnel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/source-breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetSourceBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/lost-by-delay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetLostByDelay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/recruiter-sla": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportingGetRecruiterSla"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validations/{validationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["StaffUpdateValidation"];
        trace?: never;
    };
    "/team-intel/teams/{teamId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetTeamProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/teams/{teamId}/balance-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetBalanceScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/teams/{teamId}/balance-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetBalanceAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/teams/{teamId}/recommended-hires": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetRecommendedHires"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelCompareTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-intel/dashboard-kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TeamIntelGetDashboardKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation360/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Evaluation360ListCycles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation360/cycles/{cycleId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Evaluation360GetCycleProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation360/my/rater-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Evaluation360MyRaterTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation360/my/reports/{cycleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Evaluation360MyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluation360/my/report-cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Evaluation360MyReportCycles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/critical-roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionListCriticalRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/critical-roles/{criticalRoleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetCriticalRole"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/flight-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetFlightRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/competency-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetCompetencyCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/roles-without-successor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetRolesWithoutSuccessor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/comp-gap-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetCompGapAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/critical-roles/{criticalRoleId}/suggested-successors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetSuggestedSuccessors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/critical-roles/{criticalRoleId}/simulate-exit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionSimulateExit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/succession/dashboard-kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SuccessionGetDashboardKpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/require-permission/{module}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RequirePermission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/require-org-scope/{module}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RequireOrgScope"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BalanceScoreResponse: {
            teamId: string;
            /** Format: int32 */
            memberCount: number | string;
            /** Format: int32 */
            uniqueRoles: number | string;
            /** Format: int32 */
            roleDiversity: number | string;
            /** Format: double */
            avgTenureMonths: number | string;
            /** Format: int32 */
            sizeScore: number | string;
            /** Format: int32 */
            balanceScore: number | string;
        };
        BillingConfigV1: {
            configured: boolean;
        };
        CheckoutSessionBody: {
            plan: string;
        };
        CompetencyAverage: {
            competencyKey: string;
            /** Format: double */
            average: number | string;
        };
        CompGapAlert: {
            successorId: string;
            roleId: string;
            roleTitle: string;
            userId: string;
            user: components["schemas"]["CompGapUser"];
            /** Format: double */
            currentSalary: number | string;
            currency: string;
            /** Format: double */
            midSalary: number | string;
            bandLevel: string;
            /** Format: int32 */
            gapPercent: number | string;
        };
        CompGapUser: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
        };
        CoverageRow: {
            roleId: string;
            title: string;
            criticality: string;
            /** Format: int32 */
            totalSuccessors: number | string;
            /** Format: int32 */
            readyNow: number | string;
            /** Format: int32 */
            readySoon: number | string;
            /** Format: int32 */
            developing: number | string;
            coverageStatus: string;
        };
        CriticalRoleCount: {
            /** Format: int32 */
            successors: number | string;
        };
        CriticalRoleDetailRow: {
            id: string;
            organizationId: string;
            title: string;
            positionId: null | string;
            currentHolderId: null | string;
            companyId: null | string;
            unitId: null | string;
            criticality: string;
            /** Format: double */
            flightRisk: null | number | string;
            targetBandLevel: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            currentHolder: null | components["schemas"]["HolderWithEmail"];
            successors: components["schemas"]["DetailSuccessorRow"][];
        };
        CycleProgressRow: {
            relationship: string;
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            submitted: number | string;
        };
        CycleProgressView: {
            cycleId: string;
            progress: components["schemas"]["CycleProgressRow"][];
        };
        CycleSummaryV1: {
            id: string;
            name: string;
            status: string;
            /** Format: date-time */
            opensAt: unknown;
            /** Format: date-time */
            closesAt: unknown;
            /** Format: date-time */
            publishedAt: unknown;
            /** Format: date-time */
            createdAt: unknown;
        };
        DashboardKpiView: {
            /** Format: int32 */
            totalTeams: number | string;
            /** Format: int32 */
            totalMembers: number | string;
            /** Format: int32 */
            teamsWithLeader: number | string;
            /** Format: int32 */
            teamsWithoutLeader: number | string;
            /** Format: double */
            avgTeamSize: number | string;
            /** Format: double */
            avgTenureYears: number | string;
            /** Format: double */
            diversityIndex: number | string;
        };
        DetailSuccessorRow: {
            id: string;
            organizationId: string;
            criticalRoleId: string;
            userId: string;
            readiness: string;
            type: string;
            developmentPlan: null | string;
            addedById: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            user: components["schemas"]["SuccessorUser"];
            addedByUser: null | components["schemas"]["SuccessorAddedBy"];
        };
        ExitHolder: {
            id: string;
            firstName: string;
            lastName: string;
        };
        ExitRole: {
            id: string;
            title: string;
            criticality: string;
        };
        ExitSimulationView: {
            role: components["schemas"]["ExitRole"];
            currentHolder: null | components["schemas"]["ExitHolder"];
            riskLevel: string;
            recommendation: string;
            successors: components["schemas"]["ExitSuccessorRow"][];
            /** Format: int32 */
            readyNowCount: number | string;
            /** Format: int32 */
            pipelineCount: number | string;
        };
        ExitSuccessorRow: {
            id: string;
            organizationId: string;
            criticalRoleId: string;
            userId: string;
            readiness: string;
            type: string;
            developmentPlan: null | string;
            addedById: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            user: components["schemas"]["ExitSuccessorUserView"];
        };
        ExitSuccessorUserView: {
            id: string;
            firstName: string;
            lastName: string;
            jobTitle: null | string;
        };
        ExternalAssessmentResultV1: {
            schemaVersion: string;
            assignmentId: string;
            candidateId: string;
            vacancyId: string;
            assessmentType: null | string;
            status: string;
            /** Format: date-time */
            assignedAt: unknown;
            /** Format: date-time */
            startedAt: unknown;
            /** Format: date-time */
            completedAt: unknown;
            /** Format: date-time */
            expiresAt: unknown;
            /** Format: date-time */
            scoredAt: unknown;
            /** Format: double */
            rawScore: null | number | string;
            /** Format: double */
            normalizedScore: null | number | string;
            /** Format: double */
            percentile: null | number | string;
            interpretation: null | components["schemas"]["JsonNode"];
            breakdown: null | components["schemas"]["JsonNode"];
            modelVersion: null | string;
        };
        ExternalValidationResultV1: {
            schemaVersion: string;
            id: string;
            status: string;
            /** Format: date-time */
            completedAt: unknown;
        };
        FlightRiskHolder: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
        };
        FlightRiskRow: {
            id: string;
            organizationId: string;
            title: string;
            positionId: null | string;
            currentHolderId: null | string;
            companyId: null | string;
            unitId: null | string;
            criticality: string;
            /** Format: double */
            flightRisk: null | number | string;
            targetBandLevel: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            currentHolder: null | components["schemas"]["FlightRiskHolder"];
            _count: components["schemas"]["CriticalRoleCount"];
        };
        FunnelStageView: {
            name: string;
            /** Format: int32 */
            count: number | string;
            /** Format: int32 */
            pctOfMax: number | string;
        };
        FunnelView: {
            stages: components["schemas"]["FunnelStageView"][];
            /** Format: int32 */
            totalApplications: number | string;
            /** Format: int32 */
            totalHired: number | string;
            /** Format: double */
            conversionPct: null | number | string;
        };
        HolderBasic: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
        };
        HolderWithEmail: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
            email: string;
        };
        InvoiceDetailV1: {
            subscription: null | components["schemas"]["SubscriptionV1"];
            id: string;
            /** Format: int32 */
            invoiceNumber: number | string;
            organizationId: string;
            subscriptionId: null | string;
            stripeInvoiceId: null | string;
            /** Format: double */
            amount: number | string;
            /** Format: double */
            subtotal: null | number | string;
            /** Format: double */
            taxRate: null | number | string;
            currency: string;
            status: string;
            description: null | string;
            /** Format: date-time */
            invoiceDate: unknown;
            /** Format: date-time */
            dueDate: unknown;
            poNumber: null | string;
            notes: null | string;
            memo: null | string;
            emailTo: null | string;
            emailCc: null | string;
            /** Format: date-time */
            paidAt: unknown;
            invoiceUrl: null | string;
            /** Format: date-time */
            periodStart: unknown;
            /** Format: date-time */
            periodEnd: unknown;
            /** Format: date-time */
            createdAt: unknown;
        };
        JsonNode: unknown;
        JsonObject: Record<string, never>;
        KpiView: {
            period: string;
            /** Format: int32 */
            timeToFillDays: null | number | string;
            /** Format: int32 */
            timeToHireDays: null | number | string;
            /** Format: int32 */
            hires: number | string;
            /** Format: int32 */
            offersSent: number | string;
            /** Format: int32 */
            offersAccepted: number | string;
            /** Format: int32 */
            offerAcceptRatePct: null | number | string;
            /** Format: int32 */
            totalApplications: number | string;
            /** Format: int32 */
            lostByDelay: number | string;
        };
        ListCriticalRoleRow: {
            id: string;
            organizationId: string;
            title: string;
            positionId: null | string;
            currentHolderId: null | string;
            companyId: null | string;
            unitId: null | string;
            criticality: string;
            /** Format: double */
            flightRisk: null | number | string;
            targetBandLevel: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            currentHolder: null | components["schemas"]["HolderBasic"];
            successors: components["schemas"]["ListSuccessorRow"][];
        };
        ListSuccessorRow: {
            id: string;
            organizationId: string;
            criticalRoleId: string;
            userId: string;
            readiness: string;
            type: string;
            developmentPlan: null | string;
            addedById: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            user: components["schemas"]["SuccessorUser"];
        };
        LostByDelayItem: {
            stageName: string;
            /** Format: int32 */
            slaDays: number | string;
            /** Format: int32 */
            lostCount: number | string;
            /** Format: int32 */
            avgDaysOver: number | string;
        };
        LostByDelayView: {
            /** Format: int32 */
            total: number | string;
            items: components["schemas"]["LostByDelayItem"][];
        };
        MyReportView: {
            cycleId: string;
            cycleName: string;
            buckets: components["schemas"]["ReportBucket"][];
        };
        RaterTaskSubject: {
            firstName: string;
            lastName: string;
        };
        RaterTaskV1: {
            assignmentId: string;
            cycleId: string;
            cycleName: string;
            relationship: string;
            subject: components["schemas"]["RaterTaskSubject"];
            competencies: string[];
        };
        RecruiterSlaRow: {
            name: string;
            /** Format: int32 */
            vacancies: number | string;
            /** Format: int32 */
            candidates: number | string;
            /** Format: int32 */
            avgTtfDays: null | number | string;
            /** Format: int32 */
            slaCompliancePct: null | number | string;
        };
        ReportBucket: {
            relationship: string;
            /** Format: int32 */
            raterCount: number | string;
            competencies: components["schemas"]["CompetencyAverage"][];
            comments: null | string[];
        };
        ReportCycleV1: {
            cycleId: string;
            cycleName: string;
            /** Format: date-time */
            publishedAt: unknown;
        };
        RoleWithoutSuccessorRow: {
            id: string;
            organizationId: string;
            title: string;
            positionId: null | string;
            currentHolderId: null | string;
            companyId: null | string;
            unitId: null | string;
            criticality: string;
            /** Format: double */
            flightRisk: null | number | string;
            targetBandLevel: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            currentHolder: null | components["schemas"]["HolderBasic"];
        };
        SourceBreakdownItem: {
            source: string;
            /** Format: int32 */
            applications: number | string;
            /** Format: int32 */
            hires: number | string;
        };
        StaffValidationRow: {
            id: string;
            organizationId: string;
            offerId: string;
            type: string;
            status: string;
            isBlocking: boolean;
            result: null | components["schemas"]["JsonNode"];
            completedById: null | string;
            completedByApiKeyId: null | string;
            /** Format: date-time */
            completedAt: unknown;
            notes: null | string;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
        };
        StaffValidationUpdateBody: {
            status: string;
            result?: null | components["schemas"]["JsonObject"];
            notes?: string;
        };
        SubmitValidationBody: {
            status: string;
            result: components["schemas"]["JsonObject"];
            notes?: string;
        };
        SubscriptionV1: {
            id: string;
            organizationId: string;
            stripeCustomerId: null | string;
            stripeSubscriptionId: null | string;
            plan: string;
            status: string;
            /** Format: date-time */
            currentPeriodStart: unknown;
            /** Format: date-time */
            currentPeriodEnd: unknown;
            /** Format: date-time */
            trialEndsAt: unknown;
            /** Format: date-time */
            cancelledAt: unknown;
            /** Format: date-time */
            lastStripeEventAt: unknown;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
        };
        SuccessionKpiView: {
            /** Format: int32 */
            totalCriticalRoles: number | string;
            /** Format: int32 */
            totalSuccessors: number | string;
            /** Format: int32 */
            rolesWithoutSuccessor: number | string;
            /** Format: int32 */
            coverageRate: number | string;
            /** Format: int32 */
            readyNowCount: number | string;
            /** Format: int32 */
            ready1to2YearsCount: number | string;
            /** Format: int32 */
            highFlightRiskRoles: number | string;
            /** Format: double */
            avgSuccessorsPerRole: number | string;
        };
        SuccessorAddedBy: {
            id: string;
            firstName: string;
            lastName: string;
        };
        SuccessorUser: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
        };
        SuggestedSuccessor: {
            userId: string;
            user: components["schemas"]["SuggestedUser"];
            quadrant: string;
            /** Format: double */
            potentialScore: number | string;
            /** Format: double */
            performanceScore: number | string;
            suggestedReadiness: string;
        };
        SuggestedUser: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
        };
        TeamBusinessUnitView: {
            id: string;
            name: string;
            companyId: string;
        };
        TeamComparisonLeader: {
            id: string;
            firstName: string;
            lastName: string;
        };
        TeamComparisonRow: {
            teamId: string;
            teamName: string;
            leader: null | components["schemas"]["TeamComparisonLeader"];
            /** Format: int32 */
            memberCount: number | string;
            /** Format: int32 */
            uniqueRoles: number | string;
            /** Format: double */
            avgTenureMonths: number | string;
            /** Format: int32 */
            openVacancies: number | string;
            /** Format: int32 */
            activeOkrs: number | string;
        };
        TeamComparisonView: {
            teams: components["schemas"]["TeamComparisonRow"][];
        };
        TeamCountView: {
            /** Format: int32 */
            vacancies: number | string;
            /** Format: int32 */
            okrs: number | string;
        };
        TeamLeaderView: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
            email: string;
        };
        TeamMemberUserView: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
            email: string;
            /** Format: date-time */
            createdAt: unknown;
        };
        TeamMemberView: {
            id: string;
            userId: string;
            teamId: string;
            role: string;
            /** Format: date-time */
            joinedAt: unknown;
            user: components["schemas"]["TeamMemberUserView"];
        };
        TeamProfileMember: {
            id: string;
            userId: string;
            teamId: string;
            role: string;
            /** Format: date-time */
            joinedAt: unknown;
            user: components["schemas"]["TeamProfileMemberUser"];
        };
        TeamProfileMemberUser: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: null | string;
            jobTitle: null | string;
        };
        TeamProfileView: {
            id: string;
            organizationId: string;
            businessUnitId: string;
            name: string;
            leaderId: null | string;
            settings: null | components["schemas"]["JsonNode"];
            isActive: boolean;
            /** Format: date-time */
            createdAt: unknown;
            /** Format: date-time */
            updatedAt: unknown;
            leader: null | components["schemas"]["TeamLeaderView"];
            businessUnit: null | components["schemas"]["TeamBusinessUnitView"];
            members: components["schemas"]["TeamProfileMember"][];
            _count: components["schemas"]["TeamCountView"];
        };
        TrendBucket: {
            /** Format: int32 */
            year: number | string;
            /** Format: int32 */
            month: number | string;
            /** Format: int32 */
            count: number | string;
        };
        UsageApiCalls: {
            /** Format: int32 */
            used: null | number | string;
            /** Format: int32 */
            limit: null | number | string;
        };
        UsageMetric: {
            /** Format: int32 */
            used: number | string;
            /** Format: int32 */
            limit: null | number | string;
        };
        UsageStorage: {
            /** Format: int64 */
            usedMb: null | number | string;
            /** Format: int64 */
            limitMb: null | number | string;
        };
        UsageV1: {
            employees: components["schemas"]["UsageMetric"];
            vacancies: components["schemas"]["UsageMetric"];
            assessments: components["schemas"]["UsageMetric"];
            storage: components["schemas"]["UsageStorage"];
            apiCalls: components["schemas"]["UsageApiCalls"];
            /** Format: date-time */
            periodStart: unknown;
            /** Format: date-time */
            periodEnd: unknown;
        };
        WebhookResult: {
            received: boolean;
            type: string;
            handled: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhoAmI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalWhoAmI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalGetAssessmentResults: {
        parameters: {
            query?: {
                take?: number | string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalGetAssessmentResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAssessmentResultV1"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExternalSubmitValidationResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                validationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitValidationBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalValidationResultV1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingListInvoices: {
        parameters: {
            query?: {
                take?: number | string;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingGetInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetailV1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingGetUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageV1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingGetCurrentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["SubscriptionV1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingGetConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfigV1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StripeBillingWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingCreateCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["CheckoutSessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingCreatePortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BillingCancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Precondition Failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetKpis: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KpiView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetFunnel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetSourceBreakdown: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceBreakdownItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetTrend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendBucket"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetLostByDelay: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LostByDelayView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReportingGetRecruiterSla: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecruiterSlaRow"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffUpdateValidation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                validationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffValidationUpdateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffValidationRow"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetTeamProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfileView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberView"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetBalanceScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceScoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetBalanceAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetRecommendedHires: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelCompareTeams: {
        parameters: {
            query?: {
                teamIds?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamComparisonView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamIntelGetDashboardKpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKpiView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Evaluation360ListCycles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleSummaryV1"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Evaluation360GetCycleProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleProgressView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Evaluation360MyRaterTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaterTaskV1"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Evaluation360MyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyReportView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Evaluation360MyReportCycles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCycleV1"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionListCriticalRoles: {
        parameters: {
            query?: {
                companyId?: string;
                unitId?: string;
                criticality?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCriticalRoleRow"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetCriticalRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criticalRoleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriticalRoleDetailRow"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetFlightRisk: {
        parameters: {
            query?: {
                threshold?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightRiskRow"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetCompetencyCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRow"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetRolesWithoutSuccessor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleWithoutSuccessorRow"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetCompGapAlerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompGapAlert"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetSuggestedSuccessors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criticalRoleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedSuccessor"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionSimulateExit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criticalRoleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExitSimulationView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SuccessionGetDashboardKpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessionKpiView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequirePermission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RequireOrgScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
