export const copy = {
  es: {
    language: 'English',
    welcome: 'Tu próximo paso comienza aquí',
    subtitle: 'Configura tu acceso a TIMS ATS.',
    loading: 'Verificando tu invitación…',
    unavailable: 'Esta invitación no está disponible. Solicita un nuevo enlace al administrador.',
    first: 'Nombre',
    last: 'Apellido',
    secret: 'Contraseña',
    confirm: 'Confirmar contraseña',
    create: 'Crear cuenta y unirme',
    join: 'Iniciar sesión y unirme',
    finish: 'Completar acceso',
    working: 'Preparando tu acceso…',
    policy: 'Usa entre 12 y 128 caracteres. No compartas tu clave de acceso.',
    mismatch: 'Las credenciales no coinciden.',
    error: 'No pudimos completar la configuración. Puedes volver a intentarlo sin crear otra cuenta.',
    signIn: '¿Ya tienes una cuenta? Inicia sesión',
    createInstead: 'Soy nuevo: crear cuenta',
    forgot: 'Recuperar acceso',
    recovery: 'Si tu cuenta permite recuperación por correo, recibirás un enlace. Después vuelve a esta invitación.',
    ready: 'Tu acceso está listo',
    readyText: 'Tu cuenta está conectada a la organización. Ya puedes ingresar con tus credenciales.',
    open: 'Ir a TIMS ATS',
    existing: 'Usa tus credenciales actuales. No cambiaremos tu contraseña.',
    newUser: 'Crea tus credenciales para entrar ahora y volver a ingresar cuando lo necesites.',
    wrong: 'Ingresa con el correo al que se envió esta invitación.',
    conflict: 'El administrador debe revisar tu organización o rol.',
    signinRequired: 'La cuenta puede existir ya. Ingresa o recupera tu acceso para continuar.',
    noRole: 'Acceso básico; sin permisos adicionales asignados',
    expires: 'Válida hasta',
    support: '¿Necesitas ayuda? Contacta al administrador que te invitó.',
  },
  en: {
    language: 'Español',
    welcome: 'Your next step starts here',
    subtitle: 'Set up your access to TIMS ATS.',
    loading: 'Checking your invitation…',
    unavailable: 'This invitation is unavailable. Ask your administrator for a new link.',
    first: 'First name',
    last: 'Last name',
    secret: 'Password',
    confirm: 'Confirm password',
    create: 'Create account and join',
    join: 'Sign in and join',
    finish: 'Complete setup',
    working: 'Setting up your access…',
    policy: 'Use 12–128 characters. Never share your access secret.',
    mismatch: 'The credentials do not match.',
    error: 'We could not finish setup. You can try again without creating another account.',
    signIn: 'Already have an account? Sign in',
    createInstead: 'I am new: create account',
    forgot: 'Recover access',
    recovery: 'If your account supports email recovery, you will receive a link. Then return to this invitation.',
    ready: 'Your access is ready',
    readyText: 'Your account is connected to the organization. You can now sign in.',
    open: 'Open TIMS ATS',
    existing: 'Use your current credentials. We will not change your password.',
    newUser: 'Create credentials to enter now and sign in again whenever you need to.',
    wrong: 'Sign in with the email address this invitation was sent to.',
    conflict: 'Your administrator must review your organization or role.',
    signinRequired: 'The account may already exist. Sign in or recover access to continue.',
    noRole: 'Basic access; no additional permissions assigned',
    expires: 'Valid until',
    support: 'Need help? Contact the administrator who invited you.',
  },
};
