using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using Tims.Domain.FitEngine;
using Xunit;

namespace Tims.UnitTests.Fixtures;

/// <summary>
/// Golden-parity for the pure FIT-engine kernels (Phase-5 Slice 24 / #90). Asserts
/// <see cref="FitEngineKernels"/> against the SAME contracts/fit-engine-fixtures/*.json the REAL TS service
/// exports assert (tests/fit-engine/kernels-fixtures.test.ts) — anti-drift across stacks: renormalization over
/// available weights, the all-zero-weights → {0, partial} quirk, JS half-up rounding (js-round.json pins
/// Math.round itself, including 0.49999999999999994 → 0 and −0.5 → 0), the highest-first education keyword
/// ladder, parenthetical language stripping, and the lenient typeof-guarded requirements parse. The fixture
/// expectations were GENERATED by running the TS functions — the TS is the oracle, this suite is the port's
/// proof.
/// </summary>
public sealed class FitEngineKernelsFixtureTests
{
    private static readonly JsonSerializerOptions Wire = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private static readonly JsonSerializerOptions WireDropNulls = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private static JsonArray Cases(string file) =>
        JsonNode.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "fit-engine-fixtures", file)))!
            ["cases"]!.AsArray();

    private static void AssertCase(string file, JsonNode c, JsonNode? actual)
    {
        var expected = c["expected"];
        Assert.True(
            JsonNode.DeepEquals(expected, actual),
            $"{file}: {c["name"]} — expected {expected?.ToJsonString() ?? "null"} got {actual?.ToJsonString() ?? "null"}");
    }

    [Fact]
    public void ComputeWeightedScore()
    {
        foreach (var c in Cases("weighted-score.json"))
        {
            var input = c!["input"]!;
            // The production parsers ARE the parse path under test: ParseBreakdownScores reads the five dims
            // (null/absent/non-number → null) and ParseWeights keeps number-valued keys only (?? 0 downstream).
            var raw = FitEngineKernels.ParseBreakdownScores(input["rawScores"]);
            var weights = FitEngineKernels.ParseWeights(input["weights"]);
            var actual = JsonSerializer.SerializeToNode(FitEngineKernels.ComputeWeightedScore(raw, weights), Wire);
            AssertCase("weighted-score.json", c, actual);
        }
    }

    [Fact]
    public void DeriveExperienceScore()
    {
        foreach (var c in Cases("experience-score.json"))
        {
            var input = c!["input"]!;
            double? years = input["yearsExperience"] is JsonValue v && v.GetValueKind() == JsonValueKind.Number
                ? v.GetValue<double>()
                : null;
            var requirements = FitEngineKernels.ParseRequirements(input["requirements"]);
            var actual = JsonSerializer.SerializeToNode(
                FitEngineKernels.DeriveExperienceScore(years, requirements), Wire);
            AssertCase("experience-score.json", c, actual);
        }
    }

    [Fact]
    public void DeriveEducationScore()
    {
        foreach (var c in Cases("education-score.json"))
        {
            var input = c!["input"]!;
            var requirements = FitEngineKernels.ParseRequirements(input["requirements"]);
            var actual = JsonSerializer.SerializeToNode(
                FitEngineKernels.DeriveEducationScore(input["education"], requirements), Wire);
            AssertCase("education-score.json", c, actual);
        }
    }

    [Fact]
    public void DeriveLanguageScore()
    {
        foreach (var c in Cases("language-score.json"))
        {
            var input = c!["input"]!;
            var requirements = FitEngineKernels.ParseRequirements(input["requirements"]);
            var actual = JsonSerializer.SerializeToNode(
                FitEngineKernels.DeriveLanguageScore(input["languages"], requirements), Wire);
            AssertCase("language-score.json", c, actual);
        }
    }

    [Fact]
    public void ParseRequirements()
    {
        foreach (var c in Cases("parse-requirements.json"))
        {
            // The TS result object OMITS absent fields (JSON.stringify dropped them at generation); serialize
            // the C# record dropping nulls so absent==absent, and RequiredLanguages compares as a JSON array.
            var actual = JsonSerializer.SerializeToNode(
                FitEngineKernels.ParseRequirements(c!["input"]!["raw"]), WireDropNulls);
            AssertCase("parse-requirements.json", c, actual);
        }
    }

    [Fact]
    public void JsRound()
    {
        foreach (var c in Cases("js-round.json"))
        {
            var value = c!["input"]!["value"]!.GetValue<double>();
            var actual = JsonSerializer.SerializeToNode(FitEngineKernels.JsRound(value), Wire);
            AssertCase("js-round.json", c, actual);
        }
    }
}
